[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_USE_YARN = "true"

# Optional: disable cache for Next/Tailwind
[build.processing]
  skip_processing = true

[[plugins]]
  package = "@netlify/plugin-nextjs"
